### PR TITLE
Output should reflect all SPF record strings, not just the first

### PR DESCRIPTION
**Pull request by grgras71**
Convert the entire string.

### CODE REVIEW

**Comment by konklone** [comment]
Could you provide some detail on what changes to expect from this?

**Comment by h-m-f-t** [comment]
@grgras71 reached out via other means about the change that was made here, indicating their agency has a very long SPF record which trustymail was cutting off. 

Research led to [RFC 7208](https://tools.ietf.org/html/rfc7208#section-3.3), which indicates:
>   TXT records containing multiple strings are useful in constructing
   records that would exceed the 255-octet maximum length of a
   character-string within a single TXT record.

A scan of [current-federal.csv](https://raw.githubusercontent.com/GSA/data/master/dotgov-domains/current-federal.csv) indicates that 26 federal .gov domains (second-levels) are impacted positively by this new change. Instead of only grabbing the first element in the list, @grgras71's change concatenates all strings in an SPF record together. This is good, because this change improves results for SPF records that are longer that 255 chars:

```bash
$ host -t txt cdc.gov
cdc.gov descriptive text "v=spf1 ip4:198.246.110.0/25 ip4:198.246.125.0/25 ip4:158.111.54.0/25 ip4:158.111.190.128/25 ip4:198.246.117.0/25 ip4:198.246.121.0/25 ip4:198.246.99.0/25 ip4:158.111.145.128/25 ip4:124.17.27.36 ip4:158.111.5.34 ip4:155.95.81.35 ip4:155.95.96.50 include:sp" "f.messagelabs.com ~all"
```

*and* those that are shorter but use multiple strings.

```bash
$ host -t txt feedthefuture.gov
feedthefuture.gov descriptive text "v=spf1" "mx" "ip4:208.54.243.80/32" "include:reflexion.net" "~all"
```

So this looks like a positive change, and thanks to @grgras71 for submitting it.

Before merging:
- [ ] validate that our SPF library warns when a more-than-255-char TXT record is used

**Comment by konklone** [comment]
Thank you! This is very helpful in understanding this change, and how trustymail works.

**Comment by h-m-f-t** [comment]
Thanks @grgras71, fare thee well.

**Pull request merged**
