### PR TITLE
Reconcile various supported Python versions

### PR DESCRIPTION
**Pull request by IanLee1521**
- Currently assuming the set of all that are available across setup.py, tox.ini, .travis.yml
- Also adding Python 3.7

### CODE REVIEW

**Comment by IanLee1521** [comment]
Hmm. Looks like Python 3.7 isn't supported by Travis? I'll work on that (I ran into this on my Mac which is what triggered my PR).

@h-m-f-t + @jsf9k -- Was there a decision to remove Python2 support? I see those tests fail. If Python2 is not supported, I'll update the PR to go the other way.

**Comment by jsf9k** [comment]
No decision was made to remove Python 3 support.  We did have to do that for dhs-ncats/pshtt, since nabla-c0d3/sslyze no longer supports Python 2.

I wouldn't be against dropping Python 2 support.  I don't use it, and [it is on its way out](https://pythonclock.org/).  Supporting it is [only going to become more difficult going forward](http://python3statement.org/).

Thoughts, @h-m-f-t?

**Comment by IanLee1521** [comment]
Nod. It looks like PyDNS might be pushing us towards dropping 2.x support (https://travis-ci.org/dhs-ncats/trustymail/jobs/431721269) since it seems to not install correctly...

**Comment by IanLee1521** [comment]
Hi @jsf9k -- I'm removing the `WIP:` label as this should now be ready to be merged.

It is now a removal of the Python 2 support (and addition of Python 3.7 support), due to issues that are seen with PyDNS not supporting building / installing in Python 2.7.

**Comment by jsf9k** [comment]
I wanted to bump the version since we're dropping python 2.X support.

**Review by jsf9k — APPROVED** [review]
This looks great to me!  Thank you for cleaning this up @IanLee1521!

**Pull request merged**
